version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command:
      - solr-precreate
    depends_on:
      - web
  # tor:
  #   image: goldy/tor-hidden-service:latest
  #   links:
  #     - web
  #   restart: always
  #   volumes:
  #     - "~/.keys/:/var/lib/tor/hidden_service/"
  #   environment:
  #     # Set mapping ports
  #     WEB_PORTS: "8000:8000"
  #   depends_on:
  #     - web
    

volumes:
  postgres_data:
  solr-data:
